#!/usr/bin/env bash

# Install as `build` Git alias:
#     git config alias.build '!f(){ git show origin/HEAD:build | bash -s - "$@";};f'
#
# Build debug & release targets
#     git build
# Build a single target
#     git build debug
# Build a new target with configure options and variables
#     git build gcc CC=gcc

set -euo pipefail

target_configure_args='---
_:
- --disable-shared
- --disable-install-doc
- --with-ext=openssl,psych,json,+
- cflags=-march=native

debug:
- --enable-devel
- --enable-debug-env
- cppflags=-DRUBY_DEBUG=1 -DUSE_RUBY_DEBUG_LOG=1
- optflags=-O0 -fno-omit-frame-pointer

release: []
'

targets=()
[[ $# != 0 ]] || targets=(debug release)

for target do
	case $target in
		(debug)   targets+=(debug); shift;;
		(release) targets+=(release); shift;;
	esac
done

mkdir -p target
git check-ignore -q target || echo '/target/' >> "$(git rev-parse --git-common-dir)/info/exclude"
fail() {
	set +x
	local target=$1
	shift
	>&2 echo "[$target] $*"
	return 1
}

trap -- exit INT
set -x

configure_args=(--cache-file="config.cache")
if [[ $(uname -s) = Darwin ]]; then
	brew install autoconf openssl@3 libyaml gmp
	configure_args+=(
		--with-libyaml-dir="$(brew --prefix libyaml)"
		--with-openssl-dir="$(brew --prefix openssl@3)"
		--with-gmp-dir="$(brew --prefix gmp)"
	)
elif type apt-get &>/dev/null; then
	sudo apt-get install --yes --no-install-recommends autoconf openssl libyaml-dev libgmp-dev zlib1g-dev
elif type pacman &>/dev/null; then
	sudo pacman -Sy --needed autoconf gmp libyaml zlib
fi

target_args() {
	ruby -ryaml -e 'puts YAML.load(STDIN).fetch(ARGV.shift)' "${1-_}" <<< "${target_configure_args}"
}

readarray -tO"${#configure_args[@]}" configure_args < <(target_args)

./autogen.sh
nproc=$(getconf _NPROCESSORS_ONLN)

build() {
	target=$1; shift
	target_args=("$@")
	target_args+=(--prefix="$HOME/.ruby/$target")
	mkdir -p target/"$target"
	cd target/"$target"
	if [[ ${DEBUG-} ]]; then
		./config.status --config 2>/dev/null ||:
		printf "%b\n" "${configure_args[@]}" "${target_args[@]}"
		cd -
		return
	fi
	./config.status --recheck ||
		../../configure "${configure_args[@]}" "${target_args[@]}" ||
		fail "$target" configure failed
	make -j "$nproc" || fail "$target" make failed
	cd -
}

for target in "${targets[@]}"; do
	readarray -t target_args < <(target_args "$target")
	build "$target" "${target_args[@]}"
done

[[ $# = 0 ]] && exit
[[ $# = 1 ]] && fail "$1" no configure option or variable

build "$@"
